CREATE TABLE user_project (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT REFERENCES chordtester_users(username) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    chords TEXT
)